#!/usr/bin/env bash
# Eval3 SmolVLA v10 retrain — addresses the v9 ChArUco celebrity-confusion bug.
#
# Diagnosed root cause (see tools/eval3_diagnose_celeb_confusion.py output and
# docs/eval3/charuco_pipeline.md:281): in the v9 charuco / new66_charuco
# corpora, the per-slot ChArUco-derived action labels are byte-identical across
# Taylor Swift / Yann LeCun / Barack Obama synth repos. A SmolVLA policy can
# minimise the training loss by treating action as a function of slot only and
# ignoring the language token entirely. Observed on robot: smooth grasp, wrong
# celebrity. Observed offline (tools/eval3_promptswap_quick.py):
#   v3-fresh  : pair L2 ~17 deg (Swift vs others)
#   v9 charuco: pair L2 ~6 deg (all pairs collapsed)
#
# This launcher applies Fix A + Fix B from .cursor/plans/diagnose_celeb_confusion_*.plan.md:
#
#   Fix A (data) — train on language-forcing balanced datasets generated by
#     tools/eval3_synth_dataset_gen.py --balanced --output-version v4.
#     Each dataset is one (target_celeb, ALL three slots) and the action
#     target follows where the named celebrity is placed, so the model must
#     attend to language (or perform celebrity-aware vision) to decide where
#     to reach. See `docs/eval3/charuco_pipeline.md` and the diagnostic tool
#     header for the proof.
#
#   Fix B (mix) — cap synth episode count and per-episode frame budget so the
#     real new66 corpus is no longer ~3 % of the mix. Two new env vars in
#     scripts/eval3_concat_patch.py: EVAL3_SYNTH_EPISODE_LIMIT (cap N synth
#     episodes per repo) and EVAL3_SYNTH_MAX_FRAMES_PER_EP (per-frame cap
#     applied ONLY to synth repos). Real data keeps its full budget.
#
# Recipes:
#   v4_balanced_only    : 3 v4 balanced synth datasets only
#   v4_balanced_new66   : new66 real + 3 v4 balanced synth, real upweighted
#
# Override the synth Hub list by setting EVAL3_V4_REPOS to a comma-separated
# string. By default this script assumes the v4 datasets have been pushed to
# RobotLearningVLA/dataset_v4_synth_<celeb>_balanced_1.

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RECIPE="${EVAL3_V10_RECIPE:-v4_balanced_new66}"

V4_DEFAULT="RobotLearningVLA/dataset_v4_synth_taylor_swift_balanced_1,RobotLearningVLA/dataset_v4_synth_yann_lecun_balanced_1,RobotLearningVLA/dataset_v4_synth_barack_obama_balanced_1"
V4_REPOS="${EVAL3_V4_REPOS:-$V4_DEFAULT}"

NEW66_PRIMARY="RobotLearningVLA/dataset_v2_taylor_swift_left_1_v6_truncated"
NEW66_EXTRAS="RobotLearningVLA/dataset_v2_taylor_swift_middle_1_v6_truncated,RobotLearningVLA/dataset_v2_taylor_swift_right_1_v6_truncated,RobotLearningVLA/dataset_v2_yann_lecun_left_1_v6_truncated,RobotLearningVLA/dataset_v2_yann_lecun_middle_1_v6_truncated,RobotLearningVLA/dataset_v2_yann_lecun_right_1_v6_truncated,RobotLearningVLA/dataset_v2_barack_obama_left_1_v6_truncated,RobotLearningVLA/dataset_v2_barack_obama_middle_1_v6_truncated,RobotLearningVLA/dataset_v2_barack_obama_right_1_v6_truncated"

# Split V4_REPOS into primary + extras (the first one becomes the primary)
V4_PRIMARY="$(echo "$V4_REPOS" | cut -d',' -f1)"
V4_EXTRAS="$(echo "$V4_REPOS" | cut -d',' -f2-)"

case "$RECIPE" in
  v4_balanced_only)
    export EVAL3_DATASET_REPO="${EVAL3_DATASET_REPO:-$V4_PRIMARY}"
    export EVAL3_EXTRA_REPOS="${EVAL3_EXTRA_REPOS:-$V4_EXTRAS}"
    export EVAL3_JOB_NAME="${EVAL3_JOB_NAME:-eval3-vla-v10-smolvla-fresh-v4balanced-50k}"
    export EVAL3_TRAIN_OUT="${EVAL3_TRAIN_OUT:-outputs/train/eval3-vla-v10-smolvla-fresh-v4balanced-50k}"
    # No real data here — synth episode limit not needed for balance reasons,
    # but cap each synth episode to 200 frames to keep total volume sane and
    # to discourage memorisation of long, slot-correlated trajectories.
    export EVAL3_SYNTH_EPISODE_LIMIT="${EVAL3_SYNTH_EPISODE_LIMIT:-0}"
    export EVAL3_SYNTH_MAX_FRAMES_PER_EP="${EVAL3_SYNTH_MAX_FRAMES_PER_EP:-0}"
    ;;
  v4_balanced_new66)
    export EVAL3_DATASET_REPO="${EVAL3_DATASET_REPO:-$NEW66_PRIMARY}"
    export EVAL3_EXTRA_REPOS="${EVAL3_EXTRA_REPOS:-$NEW66_EXTRAS,$V4_REPOS}"
    export EVAL3_JOB_NAME="${EVAL3_JOB_NAME:-eval3-vla-v10-smolvla-fresh-v4balanced-new66-50k}"
    export EVAL3_TRAIN_OUT="${EVAL3_TRAIN_OUT:-outputs/train/eval3-vla-v10-smolvla-fresh-v4balanced-new66-50k}"
    # new66 real ~37k frames. v4 balanced is 3 datasets x 750 eps x ~500 frames
    # ~= 1.12M frames. To get real >= ~25% of the mix, cap each v4 dataset to
    # ~75 episodes (= ~37.5k frames per repo, ~112k total synth ~= 75% mix).
    export EVAL3_SYNTH_EPISODE_LIMIT="${EVAL3_SYNTH_EPISODE_LIMIT:-75}"
    export EVAL3_SYNTH_MAX_FRAMES_PER_EP="${EVAL3_SYNTH_MAX_FRAMES_PER_EP:-0}"
    ;;
  *)
    echo "Unsupported EVAL3_V10_RECIPE=$RECIPE; expected v4_balanced_only or v4_balanced_new66" >&2
    exit 2
    ;;
esac

export EVAL3_POLICY_DEVICE="${EVAL3_POLICY_DEVICE:-cuda}"
export EVAL3_TRAIN_STEPS="${EVAL3_TRAIN_STEPS:-50000}"
export EVAL3_BATCH="${EVAL3_BATCH:-8}"
export EVAL3_SAVE_FREQ="${EVAL3_SAVE_FREQ:-10000}"
export EVAL3_MAX_FRAMES_PER_EP="${EVAL3_MAX_FRAMES_PER_EP:-600}"
export EVAL3_TASK_AUG="${EVAL3_TASK_AUG:-1}"
# Match deploy: `eval3_vla_deploy.py` and `run_eval3_deploy_battery.sh` use the
# canonical "Place the coke on <Name>" exclusively. `tools/eval3_check_deploy_command.py`
# WARNs on the "Place the coke on the <Name>" variant from v1 recordings. The
# v9 charuco runs used 0.8 here (80% canonical, 20% legacy "the" form); set to
# 1.0 in v10 so the train-time distribution exactly matches what the policy
# sees at deploy. Per DIAGNOSIS_REPORT.md section 6 ("Retrain / architecture").
export EVAL3_TASK_AUG_CANONICAL_P="${EVAL3_TASK_AUG_CANONICAL_P:-1.0}"

# Keep v6-style labels (no v8 gripper repair, no smoothing) so the real new66
# trajectories carry the celebrity-distinct dynamics that v3 partially learned.
export EVAL3_GRIPPER_REPAIR="${EVAL3_GRIPPER_REPAIR:-0}"
export EVAL3_ACTION_SMOOTH_WINDOW="${EVAL3_ACTION_SMOOTH_WINDOW:-0}"
export EVAL3_ACTION_SMOOTH_GRIPPER="${EVAL3_ACTION_SMOOTH_GRIPPER:-0}"

# v4 datasets have variable episode counts per slot but all <750 episodes
# total; keep old-data celebrity filters fully open for any legacy repos that
# get added downstream.
ALL_SYNTH_EPISODES="$(seq -s, 0 749)"
export EVAL3_SWIFT_EPISODE_FILTER="${EVAL3_SWIFT_EPISODE_FILTER:-$ALL_SYNTH_EPISODES}"
export EVAL3_LECUN_EPISODE_FILTER="${EVAL3_LECUN_EPISODE_FILTER:-$ALL_SYNTH_EPISODES}"
export EVAL3_OBAMA_EPISODE_FILTER="${EVAL3_OBAMA_EPISODE_FILTER:-$ALL_SYNTH_EPISODES}"

# Keep the latent print-shuffle / bg-replace masks OFF for synth runs (the
# extracted masks target real-print geometry).
export EVAL3_BG_REPLACE="${EVAL3_BG_REPLACE:-0}"
export EVAL3_PRINT_SHUFFLE="${EVAL3_PRINT_SHUFFLE:-0}"

# Fix C: face-preserving torchvision transform stack. Same 10 transforms as
# the v8/v9 default but:
#   - RandomErasing: p 0.3 -> 0.15, scale upper 0.10 -> 0.05, weight 0.5 -> 0.25
#       (erasing a ~10% patch can wipe an A5 face crop at our 480x640 scale)
#   - RandomPerspective: distortion 0.2 -> 0.1, p 0.5 -> 0.3, weight 1.5 -> 0.75
#       (warping degrades the small-print facial features)
#   - RandomResizedCrop: scale 0.75 -> 0.85 (avoid cropping out a face slot)
#   - GaussianBlur: sigma upper 2.0 -> 1.0 (preserve facial sharpness)
#   - ColorJitter brightness/contrast tightened 0.6-1.4 -> 0.7-1.3
#       (still defends against the LeCun<->Obama luma shortcut but doesn't
#       wash out facial detail)
# Override by exporting EVAL3_TFS_JSON before invoking this script.
DEFAULT_V10_TFS_JSON='{"brightness":{"weight":2.0,"type":"ColorJitter","kwargs":{"brightness":[0.7,1.3]}},"contrast":{"weight":2.0,"type":"ColorJitter","kwargs":{"contrast":[0.7,1.3]}},"saturation":{"weight":1.0,"type":"ColorJitter","kwargs":{"saturation":[0.5,1.5]}},"hue":{"weight":1.0,"type":"ColorJitter","kwargs":{"hue":[-0.05,0.05]}},"sharpness":{"weight":1.0,"type":"SharpnessJitter","kwargs":{"sharpness":[0.5,1.5]}},"affine":{"weight":1.0,"type":"RandomAffine","kwargs":{"degrees":[-3.0,3.0],"translate":[0.03,0.03]}},"perspective":{"weight":0.75,"type":"RandomPerspective","kwargs":{"distortion_scale":0.1,"p":0.3}},"resized_crop":{"weight":1.0,"type":"RandomResizedCrop","kwargs":{"size":[480,640],"scale":[0.85,1.0],"ratio":[0.95,1.05]}},"gaussian_blur":{"weight":0.5,"type":"GaussianBlur","kwargs":{"kernel_size":[5,9],"sigma":[0.3,1.0]}},"erase":{"weight":0.25,"type":"RandomErasing","kwargs":{"p":0.15,"scale":[0.02,0.05]}}}'
export EVAL3_TFS_JSON="${EVAL3_TFS_JSON:-$DEFAULT_V10_TFS_JSON}"

echo ">> Eval3 SmolVLA v10 recipe: $RECIPE"
echo "   synth episode limit  : $EVAL3_SYNTH_EPISODE_LIMIT"
echo "   synth max frames/ep  : $EVAL3_SYNTH_MAX_FRAMES_PER_EP"
echo "   face-preserving TFS  : enabled (Fix C; export EVAL3_TFS_JSON to override)"
exec ./scripts/run_eval3_smolvla_aug_train.sh "$@"
