#!/usr/bin/env bash
# Run offline SmolVLA checkpoint sweeps for Eval3 Train A/B/C/D (v7).
# Produces outputs/eval3_analysis/sweep_v7_{A,B,C,D}.{json,md} and a combined SUMMARY.
#
# Usage (from repo root, with venv):
#   chmod +x scripts/run_eval3_v7_checkpoint_sweeps.sh
#   ./scripts/run_eval3_v7_checkpoint_sweeps.sh
#
# Override device if needed:
#   EVAL3_SWEEP_DEVICE=cuda ./scripts/run_eval3_v7_checkpoint_sweeps.sh

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUTDIR="${ROOT}/outputs/eval3_analysis"
mkdir -p "$OUTDIR"

# Nine dataset_v2 evaluation repos (same order as eval3_smolvla_checkpoint_sweep.DEFAULT_REPOS)
REPOS="RobotLearningVLA/dataset_v2_barack_obama_left_1,RobotLearningVLA/dataset_v2_barack_obama_middle_1,RobotLearningVLA/dataset_v2_barack_obama_right_1,RobotLearningVLA/dataset_v2_yann_lecun_left_1,RobotLearningVLA/dataset_v2_yann_lecun_middle_1,RobotLearningVLA/dataset_v2_yann_lecun_right_1,RobotLearningVLA/dataset_v2_taylor_swift_left_1,RobotLearningVLA/dataset_v2_taylor_swift_middle_1,RobotLearningVLA/dataset_v2_taylor_swift_right_1"

RENAME='{"observation.images.front":"observation.images.camera1"}'

DEVICE="${EVAL3_SWEEP_DEVICE:-}"
if [[ -z "$DEVICE" ]]; then
  if command -v uv >/dev/null 2>&1; then
    DEVICE="$(uv run python - <<'PY'
import torch
if torch.backends.mps.is_available():
    print("mps")
elif torch.cuda.is_available():
    print("cuda")
else:
    print("cpu")
PY
)"
  else
    DEVICE="cpu"
  fi
fi
echo "[sweep-all] DEVICE=$DEVICE"

RUN_SWEEP() {
  local name="$1" train_dir="$2" checkpoints="$3" meta_repo="$4"
  local base="$OUTDIR/sweep_v7_${name}"
  uv run python scripts/eval3_smolvla_checkpoint_sweep.py \
    --train-dir "$train_dir" \
    --checkpoints "$checkpoints" \
    --dataset-repos "$REPOS" \
    --rename-map "$RENAME" \
    --meta-repo-id "$meta_repo" \
    --device "$DEVICE" \
    --revision v3.0 \
    --video-backend pyav \
    --frames-per-episode 2 \
    --max-samples-per-repo 24 \
    --output-json "${base}.json" \
    --output-md "${base}.md"
}

# meta-repo-id must match each track's training dataset (train_config.json dataset.repo_id).
RUN_SWEEP "A" "outputs/train/eval3_v7_A_smolvla_new" \
  "010000,020000,030000,040000,050000" \
  "RobotLearningVLA/dataset_v2_taylor_swift_left_1_v6_truncated"

RUN_SWEEP "B" "outputs/train/eval3_v7_B_smolvla_new_old" \
  "010000,020000,030000,040000,050000" \
  "RobotLearningVLA/taylor_swift_1"

RUN_SWEEP "C" "outputs/train/eval3_v7_C_warm_v3_new" \
  "003000,006000,009000,012000" \
  "RobotLearningVLA/dataset_v2_taylor_swift_left_1_v6_truncated"

# Exclude 012500 until full pretrained_model exists (all preprocessor JSON + safetensors).
RUN_SWEEP "D" "outputs/train/eval3_v7_D_obama_only" \
  "002500,005000,007500,010000" \
  "RobotLearningVLA/dataset_v2_barack_obama_left_1_v6_truncated"

uv run python - <<'PY'
import json
from pathlib import Path

out = Path("outputs/eval3_analysis")
parts = list(out.glob("sweep_v7_*.json"))
rows = []
for p in sorted(parts):
    if p.name.startswith("sweep_v7_SUMMARY"):
        continue
    tag = p.stem.replace("sweep_v7_", "")
    data = json.loads(p.read_text())
    best = data["best_checkpoint"]
    acc = next(r["summary"]["prompt_nearest_acc"] for r in data["results"] if r["step"] == best)
    facc = next(r["summary"].get("final_prompt_nearest_acc") or 0 for r in data["results"] if r["step"] == best)
    mae = next(r["summary"]["mae"] for r in data["results"] if r["step"] == best)
    rows.append((tag, best, acc, facc, mae, str(p.with_suffix(".md"))))

lines = [
    "# Eval3 v7 — offline checkpoint sweep summary",
    "",
    "Generated by `scripts/run_eval3_v7_checkpoint_sweeps.sh`. **Offline only** — not a hardware guarantee.",
    "",
    "| Track | Best step (offline rank) | prompt_nearest_acc | final_prompt_acc | MAE | report |",
    "|---|---:|---:|---:|---:|---|",
]
for tag, best, acc, facc, mae, md in rows:
    lines.append(
        f"| {tag} | {best} | {acc:.2%} | {facc:.2%} | {mae:.4f} | `{md}` |"
    )

if rows:
    by_acc = max(rows, key=lambda r: (r[2], r[3], -r[4]))
    lines.extend(
        [
            "",
            f"**Suggested hardware candidates (highest offline prompt accuracy):** start with track `{by_acc[0]}` checkpoint `{by_acc[1]}`.",
            "Also run the second-best track or a diversity pick (e.g. one warm-restart C vs fresh A).",
        ]
    )

lines.append("")
out.joinpath("sweep_v7_SUMMARY.md").write_text("\n".join(lines), encoding="utf-8")
print("Wrote", out / "sweep_v7_SUMMARY.md")
PY

echo "[sweep-all] done. See ${OUTDIR}/sweep_v7_*.md and sweep_v7_SUMMARY.md"
