#!/usr/bin/env bash
# Generate synthetic LeRobot datasets for OOD celebrities and push to HuggingFace.
#
# This is the pre-training step for the RAG SmolVLA variant.  It creates
# synthetic training episodes for celebrities that are NOT in the real
# dataset_v4_* corpus (Taylor Swift, Obama, LeCun).  The episodes are
# generated by the existing ChArUco-compositing pipeline
# (tools/eval3_synth_pins_dataset_gen.py) and then pushed to your HF account.
#
# Generated datasets are named:
#   <HF_ORG>/dataset_rag_synth_<celeb_slug>_<position>_1
# e.g.:
#   yukk1/dataset_rag_synth_elon_musk_left_1
#   yukk1/dataset_rag_synth_elon_musk_middle_1
#   yukk1/dataset_rag_synth_elon_musk_right_1
#
# Prerequisites (run once in this order):
#   1. EVAL3_INSTALL_SMOLVLA_DEPS=1 ./install.sh
#   2. ./scripts/download_pins_faces.sh          # raw Pins images (~7 GB)
#   3. python scripts/eval3_rag/build_celeb_refdb.py   # build reference face DB
#   4. python tools/pins_quality_filter.py \      # quality-rank Pins images
#        --pool-json datasets/pins-face-recognition-top30.json \
#        --out-json  datasets/pins-face-recognition-top30-quality.json
#   5. huggingface-cli login                      # authenticate as yukk1
#   6. THIS SCRIPT                                # generate + push datasets
#   7. ./scripts/eval3_rag/run_train_rag.sh       # train the RAG model
#
# Env knobs (all optional):
#   EVAL3_RAG_HF_ORG       — HF org/user to push to (default: yukk1)
#   EVAL3_RAG_PUSH_TO_HUB  — 0/1 (default 1)
#   EVAL3_RAG_WORKERS       — parallel workers (default: nproc)
#   EVAL3_RAG_POSITIONS     — comma-separated (default: left,middle,right)
#   EVAL3_RAG_CELEBS        — comma-separated slugs (default: 10 OOD celebs)
#   EVAL3_RAG_MAX_PHOTOS    — N photos per celeb (default: 5)
#   EVAL3_RAG_DISTRACTORS   — M distractor scenes per photo (default: 20)
#   EVAL3_RAG_POOL_JSON     — Pins quality JSON (default: top30-quality)
#   EVAL3_RAG_OVERWRITE     — 0/1 (default 0, skip existing)
#
# Smoke test (fast, no GPU, local only):
#   EVAL3_RAG_PUSH_TO_HUB=0 EVAL3_RAG_MAX_PHOTOS=1 EVAL3_RAG_DISTRACTORS=3 \
#   EVAL3_RAG_CELEBS=elon_musk EVAL3_RAG_POSITIONS=left \
#     ./scripts/eval3_rag/gen_rag_synth.sh
#
# Full OOD sweep with HF push:
#   EVAL3_RAG_HF_ORG=yukk1 EVAL3_RAG_PUSH_TO_HUB=1 \
#     ./scripts/eval3_rag/gen_rag_synth.sh

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
_SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
cd "$ROOT"

# ── keep alive after VSCode / SSH disconnect ──────────────────────────────────
if [[ -z "${TMUX:-}" && "${EVAL3_NO_TMUX:-0}" != "1" ]]; then
  if command -v tmux >/dev/null 2>&1; then
    SESSION="eval3_synth_$(date +%Y%m%d_%H%M%S)"
    LOG="$ROOT/outputs/logs/${SESSION}.log"
    mkdir -p "$ROOT/outputs/logs"
    _QSELF="$(printf '%q' "$_SELF")"
    _QLOG="$(printf '%q' "$LOG")"
    _QARGS=""
    for _a in "$@"; do _QARGS="${_QARGS} $(printf '%q' "$_a")"; done
    tmux new-session -d -s "$SESSION" \
      "EVAL3_NO_TMUX=1 bash ${_QSELF}${_QARGS} 2>&1 | tee ${_QLOG}"
    echo ">> Synth generation launched in tmux session '$SESSION'"
    echo "   Log        : $LOG"
    echo "   Watch live : tail -f $LOG"
    echo "   Attach     : tmux attach -t $SESSION"
    exit 0
  else
    echo ">> WARNING: tmux not found — install: sudo apt-get install -y tmux"
    echo "   Running directly (job will die if VSCode/SSH disconnects)"
  fi
fi

# shellcheck disable=SC1091
source .venv/bin/activate

HF_ORG="${EVAL3_RAG_HF_ORG:-yukk1}"
PUSH="${EVAL3_RAG_PUSH_TO_HUB:-1}"

# ── OOD celebrity targets ────────────────────────────────────────────────────
# These are the 10 celebrities from out-distribution-eval-3-pins/
# (not TOY: no taylor_swift, barack_obama, yann_lecun).
DEFAULT_CELEBS="cristiano_ronaldo,lionel_messi,rihanna,elon_musk,leonardo_dicaprio,tom_cruise,dwayne_johnson,robert_downey_jr,scarlett_johansson,jennifer_lawrence,marc_pollefeys"
CELEBS="${EVAL3_RAG_CELEBS:-$DEFAULT_CELEBS}"
POSITIONS="${EVAL3_RAG_POSITIONS:-left,middle,right}"

# ── dataset size ─────────────────────────────────────────────────────────────
# Default: N=5 photos × M=20 scenes = 100 configs per dataset.
# Full quality run: N=10, M=50 → same as v16 Pins sweep.
MAX_PHOTOS="${EVAL3_RAG_MAX_PHOTOS:-5}"
DISTRACTORS="${EVAL3_RAG_DISTRACTORS:-10}"

# MIN_PHOTOS must be > MAX_PHOTOS so the top-MAX_PHOTOS images used for
# compositing are a strict subset of what the RAG wrapper can sample for
# camera2.  The remaining (MIN_PHOTOS - MAX_PHOTOS) images appear *only* in
# camera2 during training — forcing the model to do cross-image identity
# matching instead of exact pixel lookup.  (Problem 2 fix.)
MIN_PHOTOS="${EVAL3_RAG_MIN_PHOTOS:-10}"
REFDB_DIR="${EVAL3_RAG_REFDB:-datasets/celeb_refdb}"

# ── pool JSON ────────────────────────────────────────────────────────────────
# Priority order (first found wins):
#   1. Explicit EVAL3_RAG_POOL_JSON env var
#   2. datasets/rag_pool.json  (built from celeb_refdb/ — no Pins download needed)
#   3. datasets/pins-face-recognition-top30-quality.json  (requires Pins download)
#   4. datasets/pins-face-recognition-top30.json          (fallback unfiltered)
if [[ -n "${EVAL3_RAG_POOL_JSON:-}" ]]; then
  POOL_JSON="$EVAL3_RAG_POOL_JSON"
elif [[ -f "datasets/rag_pool.json" ]]; then
  POOL_JSON="datasets/rag_pool.json"
  echo "   Using local celeb_refdb pool (no Pins download needed): $POOL_JSON"
elif [[ -f "datasets/pins-face-recognition-top30-quality.json" ]]; then
  POOL_JSON="datasets/pins-face-recognition-top30-quality.json"
  echo "   Using Pins quality pool: $POOL_JSON"
elif [[ -f "datasets/pins-face-recognition-top30.json" ]]; then
  POOL_JSON="datasets/pins-face-recognition-top30.json"
  echo "   Using Pins unfiltered pool: $POOL_JSON"
else
  echo "ERROR: No pool JSON found. Run one of:" >&2
  echo "  python scripts/eval3_rag/build_rag_pool_json.py   # lightweight, no Pins needed" >&2
  echo "  OR: ./scripts/download_pins_faces.sh && python tools/pins_quality_filter.py ..." >&2
  exit 1
fi

# ── check Pins images only if pool JSON points into the Pins dir ─────────────
if echo "$POOL_JSON" | grep -q "pins-face-recognition"; then
  PINS_DIR="datasets/pins-face-recognition/105_classes_pins_dataset"
  if [[ ! -d "$PINS_DIR" ]]; then
    echo "ERROR: Pins raw images not found at $PINS_DIR" >&2
    echo "  Run: ./scripts/download_pins_faces.sh" >&2
    echo "  OR:  use the lightweight pool: python scripts/eval3_rag/build_rag_pool_json.py" >&2
    exit 1
  fi
fi

# ── auto-populate celeb_refdb with enough portraits per OOD celeb ────────────
# Ensures MIN_PHOTOS images exist per celeb before compositing runs so that:
#   Problem 1 (diversity):   synth generator produces MAX_PHOTOS×M×3 episodes
#                            instead of 1×M×3.
#   Problem 2 (ref≠synth):  images ranked MAX_PHOTOS+1…MIN_PHOTOS only ever
#                            appear in camera2, never composited into scenes.
#   Problem 3 (resolution): CelebA-HQ supplies 1024px crops vs the 302-564px
#                            Pins fallback; higher res → sharper ChArUco warp.
#
# Source priority:
#   1. CelebA-HQ via HF streaming (entertainment celebrities, 1024×1024px)
#   2. Wikipedia REST API fallback (any public figure, incl. academics like
#      marc_pollefeys who are not in CelebA-HQ)
#
# Skip with: EVAL3_RAG_SKIP_REFDB_POPULATE=1
if [[ "${EVAL3_RAG_SKIP_REFDB_POPULATE:-0}" != "1" ]]; then
  echo ">> Checking celeb_refdb portrait counts (min=${MIN_PHOTOS} per celeb) ..."
  _NEED_CSV=""
  IFS=',' read -ra _CELEB_ARR <<< "$CELEBS"
  for _c in "${_CELEB_ARR[@]}"; do
    _n=0
    if [[ -d "$REFDB_DIR/$_c" ]]; then
      _n=$(find "$REFDB_DIR/$_c" -maxdepth 1 \
             \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) \
             2>/dev/null | wc -l | tr -d ' ')
    fi
    if [[ "$_n" -lt "$MIN_PHOTOS" ]]; then
      echo "   $_c: $_n / $MIN_PHOTOS — will fetch"
      _NEED_CSV="${_NEED_CSV:+${_NEED_CSV},}${_c}"
    else
      echo "   $_c: $_n images ✓"
    fi
  done

  if [[ -n "$_NEED_CSV" ]]; then
    echo ""
    echo "   Step 1/2: CelebA-HQ HF stream (entertainment celebrities, 1024px) ..."
    python scripts/eval3_rag/build_celeb_refdb.py \
      --db-root "$REFDB_DIR" \
      --from-hf "leondgarse/celeba_hq_face_recognition" \
      --slugs  "$_NEED_CSV" \
      --hf-max-per-celeb "$MIN_PHOTOS" || true

    # Wikipedia fallback for anyone still missing (academics, researchers, etc.)
    _WIKI_SLUGS=()
    IFS=',' read -ra _NEED_ARR <<< "$_NEED_CSV"
    for _c in "${_NEED_ARR[@]}"; do
      _n=0
      if [[ -d "$REFDB_DIR/$_c" ]]; then
        _n=$(find "$REFDB_DIR/$_c" -maxdepth 1 \
               \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) \
               2>/dev/null | wc -l | tr -d ' ')
      fi
      [[ "$_n" -lt 1 ]] && _WIKI_SLUGS+=("$_c")
    done
    if [[ ${#_WIKI_SLUGS[@]} -gt 0 ]]; then
      echo "   Step 2/2: Wikipedia fallback for: ${_WIKI_SLUGS[*]}"
      python scripts/eval3_rag/download_refdb.py \
        --db-root "$REFDB_DIR" \
        --slugs "${_WIKI_SLUGS[@]}" || true
    fi

    echo "   Rebuilding pool JSON with updated images ..."
    python scripts/eval3_rag/build_rag_pool_json.py \
      --out-json "datasets/rag_pool.json"
    POOL_JSON="datasets/rag_pool.json"
    echo ""
  fi
fi

# ── workers ──────────────────────────────────────────────────────────────────
if command -v nproc >/dev/null 2>&1; then
  DEFAULT_W=$(nproc)
else
  DEFAULT_W=$(sysctl -n hw.ncpu 2>/dev/null || echo 4)
fi
WORKERS="${EVAL3_RAG_WORKERS:-$DEFAULT_W}"
OVERWRITE="${EVAL3_RAG_OVERWRITE:-0}"

# ── source recordings ────────────────────────────────────────────────────────
# Pattern: {SOURCE_PREFIX}_{position}{SOURCE_SUFFIX}
# e.g. dataset_v5_charuko_left_1 (downloaded from SOURCE_HUB_ORG if missing).
SOURCE_PREFIX="${EVAL3_RAG_SOURCE_PREFIX:-dataset_v5_charuko}"
SOURCE_SUFFIX="${EVAL3_RAG_SOURCE_SUFFIX:-_1}"
SOURCE_HUB_ORG="${EVAL3_RAG_SOURCE_HUB_ORG:-RobotLearningVLA}"

# ── name suffix distinguishes RAG synth from existing v16 synth ──────────────
# Uses "rag1" suffix → dataset_v3_synth_rag1_<celeb>_<pos>_2
OUTPUT_SUFFIX="rag1"

echo ">> Eval3 RAG — synthetic OOD dataset generation"
echo "   pool json  : $POOL_JSON"
echo "   celebs     : $CELEBS"
echo "   positions  : $POSITIONS"
echo "   N×M        : ${MAX_PHOTOS} photos × ${DISTRACTORS} scenes = $((MAX_PHOTOS * DISTRACTORS)) configs/dataset"
echo "   source     : ${SOURCE_PREFIX}_{pos}${SOURCE_SUFFIX}  (hub: ${SOURCE_HUB_ORG:-local only})"
echo "   workers    : $WORKERS"
echo "   push hub   : $PUSH  →  org: $HF_ORG"
echo ""

# Count how many datasets will be generated
N_CELEBS=$(echo "$CELEBS" | tr ',' '\n' | grep -c '.' || true)
N_POS=$(echo "$POSITIONS" | tr ',' '\n' | grep -c '.' || true)
TOTAL=$((N_CELEBS * N_POS))
echo "   total datasets to generate: $TOTAL"
echo "   (each = dataset_v3_synth_${OUTPUT_SUFFIX}_<celeb>_<pos>_2)"
echo ""

PUSH_ARGS=()
if [[ "$PUSH" == "1" ]]; then
  PUSH_ARGS+=(--push-to-hub --hub-org "$HF_ORG")
fi

OW_ARGS=()
if [[ "$OVERWRITE" == "1" ]]; then
  OW_ARGS+=(--overwrite)
fi

exec python scripts/eval3_rag/synth_pins_gen_rag.py \
  --pool-json "$POOL_JSON" \
  --target-celebs "$CELEBS" \
  --target-positions "$POSITIONS" \
  --max-photos-per-celeb "$MAX_PHOTOS" \
  --distractors-per-target-photo "$DISTRACTORS" \
  --output-suffix "$OUTPUT_SUFFIX" \
  --source-prefix "$SOURCE_PREFIX" \
  --source-suffix "$SOURCE_SUFFIX" \
  --source-hub-org "$SOURCE_HUB_ORG" \
  --n-workers "$WORKERS" \
  "${PUSH_ARGS[@]}" \
  "${OW_ARGS[@]}" \
  "$@"
